# -*- coding: utf-8 -*-
"""test_priority

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k1iZlO_GkjyG4kfkEE0seeztNT6MwIyP
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def read_and_prep(file_path, run_no):
    try:
        df = pd.read_csv(file_path, sep=None, engine='python', encoding='utf-8-sig')
    except:
        df = pd.read_csv(file_path, sep=None, engine='python', encoding='latin1')

    df.columns = df.columns.str.strip()

    df['StatusChar'] = df['Status'].astype(str).str.strip().str.upper().apply(
        lambda x: 'F' if x == 'FAILED' else 'P'
    )
    df['IsFailed'] = df['StatusChar'].apply(lambda x: 1 if x == 'F' else 0)

    if df['ExecutionTime'].dtype == 'object':
        df['ExecutionTime'] = df['ExecutionTime'].astype(str).str.replace('s', '', regex=False)

    df['ExecutionTime'] = pd.to_numeric(df['ExecutionTime'], errors='coerce').fillna(0)

    return df[['TestID', 'Status', 'StatusChar', 'ExecutionTime', 'IsFailed']].assign(Run=run_no)


def calculate_apfd(order_df, fault_set):
    n = len(order_df)
    m = len(fault_set)

    if m == 0:
        return 0

    tf_sum = 0

    for fault_tc in fault_set:
        positions = order_df.index[order_df["TestID"] == fault_tc].tolist()
        if positions:
            tf_sum += positions[0] + 1

    apfd = 1 - (tf_sum / (n * m)) + (1 / (2 * n))
    return round(apfd, 4)


def build_fault_curve(order_df, fault_set):
    total_faults = len(fault_set)
    detected = set()

    x = []
    y = []

    for i, test_id in enumerate(order_df["TestID"], start=1):
        if test_id in fault_set:
            detected.add(test_id)

        x.append(i)
        y.append(len(detected) / total_faults if total_faults > 0 else 0)

    return x, y


try:
    # 1. Đọc dữ liệu

    files = ['run1.csv', 'run2.csv', 'run3.csv']
    all_data = [read_and_prep(f, i) for i, f in enumerate(files, 1)]
    all_runs = pd.concat(all_data, ignore_index=True)

    # 2. Tính Priority Score

    def calculate_metrics(group):
        sorted_group = group.sort_values('Run')

        trend = "-".join(sorted_group['StatusChar'].values)

        weights = np.array([0.64, 0.8, 1.0])
        failures = sorted_group['IsFailed'].values
        current_weights = weights[-len(failures):]
        wff = np.sum(failures * current_weights)

        times = sorted_group['ExecutionTime'].values
        avg_time = np.mean(times)
        std_time = np.std(times)
        cv = std_time / avg_time if avg_time > 0 else 0

        score = (10 * wff) + (1 / (avg_time * (1 + cv) if avg_time > 0 else 1))

        latest_status = sorted_group.iloc[-1]['Status']

        return pd.Series({
            'Status (Latest)': latest_status,
            'FailureTrend': trend,
            'AvgTime (s)': round(avg_time, 3),
            'Stability (CV)': round(cv, 4),
            'PriorityScore': round(score, 4)
        })

    df_result = all_runs.groupby('TestID').apply(calculate_metrics).reset_index()

    df_result = df_result.sort_values(by='PriorityScore', ascending=False)
    df_result.insert(0, 'Rank', range(1, len(df_result) + 1))

    df_result.to_csv('result_priority.csv', index=False, encoding='utf-8-sig')

    print("===== PRIORITY RESULT =====")
    print(df_result.to_string(index=False))

    # 3. Fault set chuẩn để tính APFD
    # Lấy từ Run 1

    fault_set = set(
        all_runs[
            (all_runs["Run"] == 1) &
            (all_runs["IsFailed"] == 1)
        ]["TestID"]
    )

    print("\n===== FAULT SET FROM RUN 1 =====")
    print(sorted(fault_set))
    print(f"Total faults: {len(fault_set)}")

    # 4. Tạo 3 thứ tự chạy
    # Baseline: thứ tự gốc trong Run 1
    baseline_order = (
        all_runs[all_runs["Run"] == 1][["TestID"]]
        .drop_duplicates()
        .reset_index(drop=True)
    )

    # Random: thứ tự ngẫu nhiên
    random_order = baseline_order.sample(
        frac=1,
        random_state=42
    ).reset_index(drop=True)

    # Proposed: thứ tự theo thuật toán
    proposed_order = df_result[["TestID"]].reset_index(drop=True)

    # 5. Tính APFD

    apfd_baseline = calculate_apfd(baseline_order, fault_set)
    apfd_random = calculate_apfd(random_order, fault_set)
    apfd_proposed = calculate_apfd(proposed_order, fault_set)

    print("\n===== APFD COMPARISON =====")
    print(f"Baseline APFD: {apfd_baseline}")
    print(f"Random APFD: {apfd_random}")
    print(f"Proposed Algorithm APFD: {apfd_proposed}")

    # 6. Vẽ đồ thị so sánh

    x_base, y_base = build_fault_curve(baseline_order, fault_set)
    x_rand, y_rand = build_fault_curve(random_order, fault_set)
    x_prop, y_prop = build_fault_curve(proposed_order, fault_set)

    plt.figure(figsize=(10, 6))

    plt.plot(x_base, y_base, marker="o", label=f"Baseline (APFD={apfd_baseline})")
    plt.plot(x_rand, y_rand, marker="o", label=f"Random (APFD={apfd_random})")
    plt.plot(x_prop, y_prop, marker="o", label=f"Proposed Algorithm (APFD={apfd_proposed})")

    plt.xlabel("Number of Executed Test Cases")
    plt.ylabel("Percentage of Detected Faults")
    plt.title("Fault Detection Curve: Baseline vs Random vs Proposed Algorithm")
    plt.legend()
    plt.grid(True)

    plt.savefig("apfd_comparison_graph.png", dpi=300, bbox_inches="tight")
    plt.show()

except Exception as e:
    print(f"Lỗi: {e}")