import com.kms.katalon.core.configuration.RunConfiguration

File projectDir = new File(RunConfiguration.getProjectDir())
File reportsDir = new File(projectDir, 'Reports')
File outputFile = new File(projectDir, 'Reports/katalon-test-results.csv')
outputFile.parentFile.mkdirs()

List<File> junitFiles = []
if (reportsDir.exists()) {
    reportsDir.eachFileRecurse { file ->
        if (file.name.toLowerCase().endsWith('.xml')) {
            junitFiles << file
        }
    }
}

List<String> lines = ['ID Bài Test,Trạng thái Pass/Fail,Thời gian chạy']
def slurper = new XmlSlurper(false, false)
junitFiles.each { file ->
    try {
        def xml = slurper.parse(file)
        xml.'**'.findAll { it.name() == 'testcase' }.each { tc ->
            String rawName = (tc.@name.text() ?: '').trim()
            def matcher = rawName =~ /(TC-\d{3})/
            if (!matcher.find()) return
            String id = matcher.group(1)
            boolean failed = tc.failure.size() > 0 || tc.error.size() > 0
            String status = failed ? 'FAIL' : 'PASS'
            String duration = tc.@time.text() ? "${tc.@time.text()}s" : ''
            lines << "${id},${status},${duration}"
        }
    } catch (Exception ignored) {
        // Ignore non-JUnit XML files generated by Katalon.
    }
}

outputFile.write(lines.join(System.lineSeparator()), 'UTF-8')
println "Clean CSV exported to: ${outputFile.absolutePath}"
